AIRPORTS = {
    "伦敦希思罗": {
        "iata_code": "LHR",
        "icao_code": "EGLL",
        "name": "London Heathrow Airport",
        "latitude": 51.470020,
        "longitude": -0.454295,
    },
    "上海虹桥": {
        "iata_code": "SHA",
        "icao_code": "ZSSS",
        "name": "Shanghai Hongqiao International Airport",
        "latitude": 31.197875,
        "longitude": 121.336319,
    },
    "上海浦东": {
        "iata_code": "PVG",
        "icao_code": "ZSPD",
        "name": "Shanghai Pudong International Airport",
        "latitude": 31.144344,
        "longitude": 121.808273,
    },
    "San Francisco": {
        "iata_code": "SFO",
        "icao_code": "KSFO",
        "name": "San Francisco International Airport",
        "latitude": 37.621313,
        "longitude": -122.378955,
    },
    "Washington Dulles": {
        "iata_code": "IAD",
        "icao_code": "KIAD",
        "name": "Washington Dulles International Airport",
        "latitude": 38.953116,
        "longitude": -77.456539,
    },
    "Dubai": {
        "iata_code": "DXB",
        "icao_code": "OMDB",
        "name": "Dubai International Airport",
        "latitude": 25.253174,
        "longitude": 55.365673,
    },
}


AIRPORT_ALIASES = {
    "london heathrow": "伦敦希思罗",
    "heathrow": "伦敦希思罗",
    "lhr": "伦敦希思罗",
    "egll": "伦敦希思罗",
    "shanghai hongqiao": "上海虹桥",
    "sha": "上海虹桥",
    "zsss": "上海虹桥",
    "shanghai pudong": "上海浦东",
    "pvg": "上海浦东",
    "zspd": "上海浦东",
    "san francisco": "San Francisco",
    "san francisco international": "San Francisco",
    "旧金山": "San Francisco",
    "sfo": "San Francisco",
    "ksfo": "San Francisco",
    "washington dulles": "Washington Dulles",
    "washington dulles international": "Washington Dulles",
    "华盛顿杜勒斯": "Washington Dulles",
    "iad": "Washington Dulles",
    "kiad": "Washington Dulles",
    "dubai": "Dubai",
    "dubai international": "Dubai",
    "迪拜": "Dubai",
    "dxb": "Dubai",
    "omdb": "Dubai",
}


BA_A380_REGISTRATIONS = tuple(f"G-XLE{letter}" for letter in "ABCDEFGHIJKL")


AIRLINE_ALIASES = {
    "英国航空": "British Airways",
    "美国航空": "American Airlines",
    "美国联合航空": "United Airlines",
    "维珍大西洋航空": "Virgin Atlantic",
}


AIRLINE_CODES = {
    "KM马耳他航空": ("KM", "KMM"),
    "以色列航空": ("LY", "ELY"),
    "伊比利亚航空": ("IB", "IBE"),
    "伏林航空": ("VY", "VLG"),
    "冰岛航空": ("FI", "ICE"),
    "加拿大航空": ("AC", "ACA"),
    "卡塔尔航空": ("QR", "QTR"),
    "卢旺达航空": ("WB", "RWD"),
    "印度航空": ("AI", "AIC"),
    "国泰航空": ("CX", "CPA"),
    "土耳其航空": ("TK", "THY"),
    "埃及航空": ("MS", "MSR"),
    "塞尔维亚航空": ("JU", "ASL"),
    "新加坡航空": ("SQ", "SIA"),
    "沙特航空": ("SV", "SVA"),
    "法国航空": ("AF", "AFR"),
    "波兰航空": ("LO", "LOT"),
    "泰国国际航空": ("TG", "THA"),
    "洛根航空": ("LM", "LOG"),
    "澳洲航空": ("QF", "QFA"),
    "爱尔兰航空": ("EI", "EIN"),
    "瑞士航空": ("LX", "SWR"),
    "科威特航空": ("KU", "KAC"),
    "维珍大西洋航空": ("VS", "VIR"),
    "美国联合航空": ("UA", "UAL"),
    "美国航空": ("AA", "AAL"),
    "英国航空": ("BA", "BAW"),
    "British Airways": ("BA", "BAW"),
    "American Airlines": ("AA", "AAL"),
    "United Airlines": ("UA", "UAL"),
    "Virgin Atlantic": ("VS", "VIR"),
    "葡萄牙航空": ("TP", "TAP"),
    "西捷航空": ("WS", "WJA"),
    "越南航空": ("VN", "HVN"),
    "达美航空": ("DL", "DAL"),
    "阿提哈德航空": ("EY", "ETD"),
    "阿联酋航空": ("EK", "UAE"),
    "黎巴嫩航空": ("ME", "MEA"),
}
